name: Build & Deploy Static Flask Site to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.13.0
  BUILD_DIR: build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Also ensure Frozen-Flask is there (if not already)
          pip install frozen-flask

      - name: Load environment variables
        run: |
          # Load DB/API secrets into environment
          # (Recommended: store as GitHub Secrets: DATABASE_URL, API_KEY, etc.)
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> $GITHUB_ENV
          echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> $GITHUB_ENV

      - name: Freeze the Flask app into static files
        run: |
          # Create a script freeze.py in your repo root:
          # from flask_frozen import Freezer
          # from app import app
          # freezer = Freezer(app)
          # if __name__ == '__main__':
          #     freezer.freeze()
          python freeze.py
        env:
          FLASK_ENV: production

      - name: Upload build directory
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: ${{ env.BUILD_DIR }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: static-site
          path: .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ${{ env.BUILD_DIR }}
